Cache: use null adapter while redis isn't ready
iFixit/react-commerce pull request #1339
Opened 2023-02-07 09:02 UTC by danielbeardsley

We seem to be getting about [~250 errors per day](https://app.datadoghq.com/logs?query=source%3Avercel%20service%3Areact-commerce-prod.vercel.app%20status%3Aerror%20writeable&agg_m=count&agg_q=%40path&agg_t=count&cols=host%2Cservice&index=&messageDisplay=inline&stream_sort=time%2Cdesc&top_n=5&top_o=top&viz=stream&from_ts=1675155609590&to_ts=1675760409590&live=true) that say the redis connection isn't a writable stream. These should be able to be caught and dealt with by returning as a miss, but they seem to be aborting the request.

Redis is communicated with via a persistent connection, so here we change caching to dynamically choose the backend based on the connection state. If it's anything other than "ready", we use the null adapter (everything looks like a miss).

Possible connection states from Typescript:
```typescript
type RedisStatus = "wait"
  | "reconnecting"
  | "connecting"
  | "connect"
  | "ready"
  | "close"
  | "end"
```

Looking at the client code, checking for `ready` seems like the right choice. I've also upped the connection timeout now that we have a fallback while connecting and that connecting won't delay any requests.

2023-02-07 15:36 UTC, dhmacs requested changes
It looks like they're all background revalidation requests to `api/nextjs/cache/product`, so they don't affect the user and it doesn't help to use the null adapter since the goal of these requests is to revalidate the Redis cache

deploy_block 🛑  let's take some time to inspect the error and find a fix

2023-02-07 17:57 UTC, danielbeardsley commented
> It looks like they're all background revalidation requests to `api/nextjs/cache/product`

Sorry, I had the query wrong, I've updated the link to show that it's happening on user requests too, but we catch those errors and treat them as misses correctly so they aren't 500s.

I've tried to look for a cause, but I haven't found anything obvious. I have noticed that they come in short 1-2 second bursts separated by many minutes of no errors. "Stream isn't writable" means the underlying TCP connection to redis is down for the moment, so attempting requests won't do anything. I do want this condition to be somewhat visible because I want to know if it gets worse or better. That said, I don't expect to be able to fix occasional connection interruptions with a 3rd party service.

I can try reducing our reconnection delay, perhaps we can recover more quickly, I'll open a pull.

Here's an example of the timestamps
![image](https://user-images.githubusercontent.com/26855/217323698-e77f4c8f-df92-4a73-ad77-2b46cbd0c97f.png)

2023-02-08 21:01 UTC, erinemay commented
@danielbeardsley thoughts on testing this?

2023-02-08 22:50 UTC, danielbeardsley commented
I think we should wait on the QA till I fix the conflicts.

Testing: run it locally with the REDIS_URL set to something that won't work: `redis://example.com` or some such. You shouldn't see any errors when accessing product pages. You can throw some log statements into the null adapter to ensure it's being used.

dev_block :+1: on fixing conflicts.

2023-03-06 17:58 UTC, danielbeardsley commented
This setting now just returns errors (effectively misses) when it can't connect to redis so this is no longer needed:
https://github.com/iFixit/react-commerce/blob/af589472e8106052f44f49f1d6907f8357062a1d/frontend/lib/redis/index.ts#LL18C12-L18C12

2023-03-06 17:58 UTC, closed without merging