Upgrade algolia instantsearch
iFixit/react-commerce pull request #1525
Opened 2023-04-03 10:44 UTC by federicobadini

closes #1382 
closes #1487 

This PR introduces the new `react-instantsearch-hooks-router-nextjs` package.
With this new package, the nextjs router now plays nicely with Algolia.

On the Algolia side there is still [this pending issue](https://github.com/algolia/instantsearch/issues/5571) that required a little hack

### QA

1. Visit Vercel preview
2. Verify that the browser back button is working correctly
3. Verify that the item type name persisting in the hero section is now fixed

2023-04-03 15:07 UTC, jordycosta commented
QA 🟢 

The back button is still working as expected ✅ 
The title is now updated and https://github.com/iFixit/react-commerce/issues/1487 no longer persists ✅ 

### Testing Procedure:

1. Go to the [Vercel Preview](https://react-commerce-git-fix-item-type-name-persisting-863b89-ifixit.vercel.app/Parts/iPhone)
2. Add an item type selection in the UI _(e.g. Accessories)_
3. Refresh the page
4. Remove the item type selection

> Ensure that the title of the page is updated correctly

2023-04-03 15:14 UTC, masonmcelvain requested changes
CR ✌🏻 I'm excited to see this change, thank you! dev_block ✌🏻 on the negative page param bug. Up to you if you'd like to remove `deviceItemType` from the productList model or not, we could always do it in another PR.

2023-04-03 15:14 UTC, masonmcelvain commented on frontend/components/common/InstantSearchProvider.tsx
> +            p: typeof p === 'string' ? parseInt(p) : undefined,
Dropping the non-negative check on `p` can cause the page to 500, for example visiting `/Parts?p=-1`

2023-04-04 10:35 UTC, federicobadini commented
un_dev_block ✌🏻
Cleaned deviceItemType and restored the non-negative check

2023-04-04 16:18 UTC, masonmcelvain approved these changes
CR ✌🏻 Thanks for the changes!

2023-04-04 18:20 UTC, merged