Add logs to graphql queries
iFixit/react-commerce pull request #174
Opened 2022-02-16 15:12 UTC by dhmacs

closes #141 

cc @lithobraking @sterlinghirsh @andyg0808 

## Changelog

- Add better logging to graphql requests

## QA

There's not an easy way to promt Strapi to return errors in order to verify error logging. The way I did it while developing is by sending wrong queries on purpose.
If you want to reproduce an error yourself you need to clone the repo and replace this: https://github.com/iFixit/react-commerce/blob/094f877d2b90d464b970dda603e4692e8f6e7ec2/frontend/lib/strapi-sdk/index.ts#L16 with this:
```ts
         variables: {
            filters: {
               foo: 'bar',
            },
         },
```
Start the dev server (`npm run dev`) then navigate a product list page and you'll see an error like this on your terminal:

<img width="680" alt="Screenshot 2022-02-16 at 16 08 38" src="https://user-images.githubusercontent.com/4640135/154293766-128a6ba2-e2e8-4602-9631-1c29fe43d9e2.png">

2022-02-16 19:28 UTC, deltuh-vee commented
QA 🎬
GraphQL errors are now logged.

Just curious, will these logs end up in Sentry or somewhere else?

2022-02-16 23:43 UTC, masonmcelvain commented
CR ✌🏻

2022-02-17 00:16 UTC, danielbeardsley commented on frontend/lib/strapi-sdk/index.ts
> +      console.log('GraphQL query failed with errors:');
```suggestion
      console.error('GraphQL query failed with errors:');
```

2022-02-17 00:16 UTC, danielbeardsley commented on frontend/lib/strapi-sdk/index.ts
> +         console.log(`\t[${code}]`, error.message);
```suggestion
         console.error(`\t[${code}]`, error.message);
```

2022-02-17 00:17 UTC, danielbeardsley requested changes
Looks good, just a couple of suggestions

2022-02-17 09:36 UTC, danielbeardsley commented
CR :+1:

2022-02-17 17:32 UTC, deltuh-vee commented
Carry Over QA 🎬

2022-02-18 09:47 UTC, merged