Set itemType on Server
iFixit/react-commerce pull request #998
Opened 2022-11-07 20:57 UTC by sumukhipandey

This PR is basically a revert of this commit https://github.com/iFixit/react-commerce/commit/5155bbcca4ecfc6e7d287e91f7ca53bf10c3ba70 We got rid of this feature and upgraded to instantSearch, but this was causing a weird loading pattern.

Closes #783 

CC: @masonmcelvain

2022-11-07 22:37 UTC, masonmcelvain requested changes
CR ✌🏻 Nice work @sumukhipandey! This adds `productList.deviceItemType` on the server, but doesn't yet use it anywhere. We need to add it in the hook (like in this commit https://github.com/iFixit/react-commerce/commit/a5481b5c597546946dd30bb5c24bf05bdfcdae9b) so that the app can use it on the server.

2022-11-07 22:37 UTC, masonmcelvain commented on frontend/components/common/InstantSearchProvider.tsx
> +            const itemTypeHandle = pathParts.length >= 3 ? pathParts[2] : '';
This var doesn't get used anywhere, so I don't think we need it

2022-11-07 22:37 UTC, masonmcelvain commented
forgot to dev_block ✌🏻 on that

2022-11-09 23:02 UTC, masonmcelvain submitted a review, later dismissed
CR ✌🏻 I think this is right, nice work!

2022-11-09 23:03 UTC, masonmcelvain commented
un_dev_block ✌🏻

2022-11-10 19:36 UTC, erinemay commented
dev_block 🌱 
The breadcrumbs got a smidge messed up:
![image](https://user-images.githubusercontent.com/72166715/201187701-e2203dda-810b-42cb-b7fe-da67fb6b35e0.png)
https://react-commerce-git-set-item-type-on-server-ifixit.vercel.app/Parts/Mac/Bluetooth_Board

Note: It looks like what you're trying to do worked. There's an intermediate point during page load that shows the item type name is getting loaded instead of "Parts". It just finishes loading and looks like it does in that first image ☝️ 
![image](https://user-images.githubusercontent.com/72166715/201188773-a891c765-e7b4-4366-a2a3-2860edd7734a.png)

I attached a couple of screen recordings with the speed toggled way down so you can see how the page loads:

<details><summary>Branch</summary>

https://user-images.githubusercontent.com/72166715/201189058-88886c25-71cd-483d-ac67-0423b32d81f6.mp4

</details>

<details><summary>Main</summary>

https://user-images.githubusercontent.com/72166715/201189072-9e1b7697-d8d9-4e15-9d72-96223de03a51.mp4

</details>

2022-11-10 23:03 UTC, sumukhipandey commented
> dev_block 🌱 The breadcrumbs got a smidge messed up: ![image](https://user-images.githubusercontent.com/72166715/201187701-e2203dda-810b-42cb-b7fe-da67fb6b35e0.png) https://react-commerce-git-set-item-type-on-server-ifixit.vercel.app/Parts/Mac/Bluetooth_Board
> 
> Note: It looks like what you're trying to do worked. There's an intermediate point during page load that shows the item type name is getting loaded instead of "Parts". It just finishes loading and looks like it does in that first image ☝️ ![image](https://user-images.githubusercontent.com/72166715/201188773-a891c765-e7b4-4366-a2a3-2860edd7734a.png)
> 
> I attached a couple of screen recordings with the speed toggled way down so you can see how the page loads:
> 
> Branch
> Main

Thanks Erin! I am not sure what's causing the breadcrumbs bug here... @masonmcelvain do you have any idea as to why this might've happened?

2022-11-11 00:10 UTC, erinemay commented
I've seen this exact issue pop up on a pull semi-recently. I'm gonna hunt for it.

2022-11-11 00:26 UTC, masonmcelvain commented
Thank you @erinemay! I knew we had seen this before. I'm also looking into it.

2022-11-11 00:41 UTC, masonmcelvain commented
un_dev_block ✌🏻 Super strange behavior, I can't explain why the breadcrumbs were borked. Regardless, we solved the problem before by not using the SSR hack for the breadcrumbs, so let's reuse that solution. (@danielbeardsley)

2022-11-11 18:17 UTC, k0rvusk0r4x commented
- Breadcrumbs are no longer messed up.
- I am not seeing the incorrect loading behavior.

QA 😺

2022-11-11 19:35 UTC, danielbeardsley commented on frontend/templates/product-list/sections/FilterableProductsSection/useDevicePartsItemType.tsx
> +   if (typeof window === 'undefined' && productList.deviceItemType) {
I kinds feel like this whole routine is somewhat convoluted. I'm gonna try something.

2022-11-11 20:03 UTC, danielbeardsley commented on frontend/templates/product-list/sections/FilterableProductsSection/useDevicePartsItemType.tsx
> +   if (typeof window === 'undefined' && productList.deviceItemType) {
The pushed commit seems to not create the bookmarks weirdness and I feel it's clearer to read.

2022-11-11 20:03 UTC, danielbeardsley commented
CR :+1:

2022-11-11 20:03 UTC, danielbeardsley approved these changes
CR :+1:

2022-11-11 23:21 UTC, k0rvusk0r4x commented
Continues to function the same as [here](https://github.com/iFixit/react-commerce/pull/998#issuecomment-1312030669).

QA 😺

2022-11-11 23:22 UTC, merged